"""Beta credential slot management — quick-add tester workflow.

Reads / writes `data/beta_credentials_master.csv`, the cleartext-password
register generated by `scripts/generate_beta_credentials.py`.

The JSON store `data/beta_signups.json` is pre-populated with 20 approved
slots; this module never touches the JSON (PII would land in git). Real
tester names + emails stay LOCAL in the CSV only.

Use case
--------
When a signed NDA comes back from a tester (off-platform — via email
reply, not the signup form), the admin uses the "📋 Slots" tab on
/Beta_Admin to:

  1. Pick the next free slot (slot_status() returns the table)
  2. Paste tester's real name + email + organisation
  3. Click Assign → returns (login_email, cleartext_password) ready to
     drop into the welcome email
"""

from __future__ import annotations

import csv
import io
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import pandas as pd


_ROOT     = Path(__file__).parent.parent.parent
CREDS_CSV = _ROOT / "data" / "beta_credentials_master.csv"


CREDS_FIELDS = [
    "slot", "login_email", "password",
    "email_sent", "email_replied",
    "assigned_to_real_name", "assigned_to_real_email", "organisation",
    "assigned_at", "credentials_sent_at",
]


def col_or(df, *candidates) -> Optional[str]:
    """Return the first matching column name in df, case-insensitive.
    Tolerates user-renamed columns: 'Email Sent' / 'email_sent' / 'emailSent'
    all resolve to the same logical field.
    """
    lower_map = {c.lower().strip(): c for c in df.columns}
    for cand in candidates:
        if cand in df.columns:
            return cand
        hit = lower_map.get(cand.lower().strip())
        if hit:
            return hit
    return None


# ── CSV I/O ──────────────────────────────────────────────────────────────
def load_credentials_csv() -> pd.DataFrame:
    """Read the credential master into a DataFrame. Empty if no CSV yet."""
    if not CREDS_CSV.exists():
        return pd.DataFrame(columns=CREDS_FIELDS)
    return pd.read_csv(CREDS_CSV, keep_default_na=False, dtype=str)


def _save_credentials_csv(df: pd.DataFrame) -> None:
    CREDS_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(CREDS_CSV, index=False, quoting=csv.QUOTE_ALL)


def slot_status() -> pd.DataFrame:
    """All slots with derived 'status' column (free / assigned)."""
    df = load_credentials_csv()
    if df.empty:
        return df
    df = df.copy()
    df["status"] = df["assigned_to_real_email"].apply(
        lambda e: "✅ assigned" if str(e).strip() else "🟢 free"
    )
    # Order: free slots first (so admin always sees the next available)
    order_key = df["status"].map({"🟢 free": 0, "✅ assigned": 1}).fillna(2)
    return df.assign(_o=order_key).sort_values(["_o", "slot"]).drop(columns="_o").reset_index(drop=True)


def free_slots() -> pd.DataFrame:
    """Just the unassigned slots."""
    df = load_credentials_csv()
    if df.empty:
        return df
    return df[df["assigned_to_real_email"].astype(str).str.strip() == ""].reset_index(drop=True)


# ── Assignment ───────────────────────────────────────────────────────────
def assign_slot_to_tester(
    real_name:    str,
    real_email:   str,
    organisation: str = "",
    slot:         Optional[str] = None,
) -> dict:
    """Assign a slot to a real tester. Updates CSV in place.

    If `slot` is None, the next free slot is auto-selected.
    Returns the full assigned row as a dict, including cleartext password
    (so the caller can render a copy-paste welcome email card).

    Raises:
        ValueError if no free slots, or the named slot is already taken,
        or required fields are blank.
    """
    real_name  = (real_name  or "").strip()
    real_email = (real_email or "").strip().lower()
    organisation = (organisation or "").strip()

    if not real_name:
        raise ValueError("Real name is required.")
    if "@" not in real_email or "." not in real_email.split("@")[-1]:
        raise ValueError("Real email looks invalid.")

    df = load_credentials_csv()
    if df.empty:
        raise ValueError(
            "No credential slots exist yet. Run "
            "`python scripts/generate_beta_credentials.py 20` first."
        )

    # Prevent double-booking a tester across slots
    already = df[df["assigned_to_real_email"].str.lower() == real_email]
    if not already.empty:
        raise ValueError(
            f"{real_email} is already assigned to slot "
            f"{already.iloc[0]['slot']}."
        )

    # Pick the slot
    free = df[df["assigned_to_real_email"].astype(str).str.strip() == ""]
    if slot:
        candidate = df[df["slot"] == slot]
        if candidate.empty:
            raise ValueError(f"Slot {slot} does not exist.")
        if candidate.iloc[0]["assigned_to_real_email"].strip():
            raise ValueError(
                f"Slot {slot} is already assigned to "
                f"{candidate.iloc[0]['assigned_to_real_email']}."
            )
        idx = candidate.index[0]
    else:
        if free.empty:
            raise ValueError(
                "All slots are assigned. Generate more with: "
                "`python scripts/generate_beta_credentials.py 10`"
            )
        idx = free.index[0]

    # Mutate
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    df.at[idx, "assigned_to_real_name"]  = real_name
    df.at[idx, "assigned_to_real_email"] = real_email
    df.at[idx, "organisation"]           = organisation
    df.at[idx, "assigned_at"]            = now_iso

    _save_credentials_csv(df)
    return df.loc[idx].to_dict()


def mark_credentials_sent(slot: str) -> bool:
    """Stamp the sent timestamp once the admin actually emails the tester."""
    df = load_credentials_csv()
    if df.empty:
        return False
    mask = df["slot"] == slot
    if not mask.any():
        return False
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    df.loc[mask, "credentials_sent_at"] = now_iso
    _save_credentials_csv(df)
    return True


def unassign_slot(slot: str) -> bool:
    """Clear an assignment — e.g. tester declined or wrong slot picked."""
    df = load_credentials_csv()
    if df.empty:
        return False
    mask = df["slot"] == slot
    if not mask.any():
        return False
    for col in ("assigned_to_real_name", "assigned_to_real_email",
                "organisation", "assigned_at", "credentials_sent_at"):
        df.loc[mask, col] = ""
    _save_credentials_csv(df)
    return True


# ── Welcome email builder ────────────────────────────────────────────────
DASHBOARD_URL = os.environ.get(
    "DASHBOARD_URL",
    "https://rates-dashboard-6gmz8swptjxoapenjwptgm.streamlit.app",
)


def build_welcome_email_text(
    real_name:   str,
    login_email: str,
    password:    str,
    organisation: str = "",
    dashboard_url: str = DASHBOARD_URL,
) -> tuple[str, str]:
    """Returns (subject, body) ready to paste into Gmail."""
    first_name = real_name.split()[0] if real_name else "there"
    subject = "You're in — Macro Manv beta access details"
    body = f"""\
Hi {first_name},

Thanks for signing the NDA and Beta Terms — you're in.

Your access:

    URL:       {dashboard_url}
    Login:     {login_email}
    Password:  {password}

(The login email is an internal slot identifier — you don't need to read
mail at that address. Just use it as your username on the login form.)

ONE IMPORTANT REMINDER — please access the dashboard only from a
personal device on a personal network (home WiFi, mobile hotspot, or
personal-tethered 5G). Not your work laptop, work WiFi, or corporate
VPN. Beta Terms § 4.2(h) — see the PDF you signed for the why.

What to look at first:

  1. 📐 Methodology — every formula documented; start here so the rest
     of the dashboard makes sense
  2. 🔍 Scanner — the ranked RV trade board (start with 2s10s curves)
  3. 📊 Backtester — pick any trade from the Scanner, run a 12-month
     backtest, look at the four-component P&L decomposition
  4. 🎯 Trade Builder — DV01-neutral ticket math
  5. ⚡ Regime — current macro regime + conditional Sharpe table

Two weeks from today the Structured Feedback Form lands in your inbox.
In the meantime, just reply to this email if anything is broken or
unclear. The smallest "this column is confusing" notes are the most
useful.

— Manv
"""
    return subject, body
